### ISSUE TITLE
FR/Suggestions/Discussions

### ISSUE THREAD

**Issue by edalzell** [tavando/Statamify#1]
Hey there Lucas, amazing job on this....soooooo much work!!

I've started to look at this and I have a few thoughts suggestions on next steps to make this releasable to the general public.
Changes:

- put all addons under `Statamify`
- move to OmniPay so there aren't 2 additional addons for the payment gateways
- move `Customers` to Users (will make logging in later to see order status a lot easier)
- Store Orders in a DB (could be a lot of them and wouldn't want to slow down the site)
- make an "installer" to gather all the relevant information

Naturally should do only one of these at a time so-as not to muck anything else up.

@tavando let me know if this isn't appropriate of if you'd rather discuss another way.

**Comment by tavando** [comment]
@edalzell Hi Erin! Thanks for the insights.

I think Github is fine for suggestions. We could accompany it with public Trello board - but that's the idea for later?

In general - I need help with it. Pull request are needed from other contributors, because I can't do everything by myself (actually I did, but that's for my clients that I can modify as much as I want).

Whole code needs revision - especially structure. Statamic somehow limited me, but maybe there are ways to refactor it in more "production" style (put everything into MVC model).

I still want to keep it simple, so everything that extends Statamify with non-standard features, should be put in addons.

About your suggestions (should we split it into separate Issues?)
- addons under Statamify: I tried, but I had problems with it, there was no time to dig deeper
- OmniPay: I haven't known this, looks cool!
- Customers: I wanted to keep customers separate from users - not all users are customers. Customer is when you buy something. Moreover, you would have to add fields to existing user profile and it can collide with other fields from other addons for example
- Everything in DB: I want admin/developer to have choice. To use files or database. Connecting to DB slows down site too. Maybe we could also implement connecting to external DBs, like Firebase for scalability.
- Installer: yes, I thought about this too

**Comment by edalzell** [comment]
> Customers: I wanted to keep customers separate from users - not all users are customers. Customer is when you buy something. Moreover, you would have to add fields to existing user profile and it can collide with other fields from other addons for example

How are you going to handle customers logging in to see order status, change account info? You can diff permissions for roles so customer don't have any access to CP, only their order?

I can understand leaving this one the way it is though...just gotta work through the login side of things. Their access should be all front end anyway so maybe it's not a big deal.

**Comment by edalzell** [comment]
> put all addons under Statamify

Put into https://github.com/tavando/Statamify/issues/2

**Comment by edalzell** [comment]
> move to OmniPay so there aren't 2 additional addons for the payment gateways

Put into https://github.com/tavando/Statamify/issues/3

**Comment by edalzell** [comment]
> make an "installer" to gather all the relevant information

Put into https://github.com/tavando/Statamify/issues/4

**Comment by edalzell** [comment]
> Store Orders in a DB (could be a lot of them and wouldn't want to slow down the site)

Discussion [here](https://github.com/tavando/Statamify/issues/5)

**Comment by edalzell** [comment]
> move Customers to Users (will make logging in later to see order status a lot easier)

Discussion [here](https://github.com/tavando/Statamify/issues/6).

**Comment by edalzell** [comment]
All issues/discussions moved to individual issues
